# Generated by Django 2.0.1 on 2018-01-25 19:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[['W', 'White'], ['U', 'Blue'], ['B', 'Black'], ['R', 'Red'], ['G', 'Green'], ['C', 'Colorless'], ['N', 'Generic']], max_length=20),
        ),
    ]
