# Generated by Django 2.0.1 on 2018-01-25 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_auto_20180125_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='mana_Cost',
            new_name='mana_cost',
        ),
    ]
