# Generated by Django 2.0.1 on 2018-01-25 21:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_auto_20180125_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_subtypes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='card',
            name='colors',
            field=multiselectfield.db.fields.MultiSelectField(choices=[['W', 'White'], ['U', 'Blue'], ['B', 'Black'], ['R', 'Red'], ['G', 'Green'], ['C', 'Colorless'], ['N', 'Generic']], max_length=100),
        ),
    ]
