# Generated by Django 2.0.1 on 2018-01-29 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_auto_20180126_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='cards',
        ),
        migrations.AddField(
            model_name='card',
            name='from_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='card.Set'),
        ),
    ]
