# Generated by Django 2.0.1 on 2018-01-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_auto_20180129_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
