# Generated by Django 2.0.1 on 2018-01-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_card_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
