# Generated by Django 2.0.1 on 2018-02-06 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_auto_20180129_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='set_id',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
