# Generated by Django 2.0.1 on 2018-02-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0012_set_set_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
