# Generated by Django 2.0.1 on 2018-02-06 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0013_set_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='rares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Rares', to='card.Set'),
        ),
    ]
