# Generated by Django 2.0.1 on 2018-02-06 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0014_card_rares'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Commons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Commons', to='card.Set'),
        ),
        migrations.AddField(
            model_name='card',
            name='uncommons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uncommons', to='card.Set'),
        ),
    ]
