# Generated by Django 2.0.1 on 2018-02-06 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_auto_20180206_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='Commons',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commons', to='card.Set'),
        ),
        migrations.AlterField(
            model_name='card',
            name='rares',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rares', to='card.Set'),
        ),
    ]
