# Generated by Django 2.0.1 on 2018-02-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0017_auto_20180206_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
