# Generated by Django 2.0.1 on 2018-02-15 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0021_auto_20180215_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='back_side',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='front_side', to='card.Card'),
        ),
    ]
