# Generated by Django 2.0.1 on 2018-02-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0022_auto_20180215_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='in_pack',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
