# Generated by Django 2.0.1 on 2018-03-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0023_card_in_pack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('deck_format', models.CharField(choices=[['ST', 'Standard'], ['SE', 'Sealed'], ['DR', 'Draft']], max_length=50)),
                ('card_list', models.ManyToManyField(to='card.Card')),
            ],
        ),
        migrations.AddField(
            model_name='set',
            name='sealed_format',
            field=models.ManyToManyField(related_name='_set_sealed_format_+', to='card.Set'),
        ),
    ]
