# Generated by Django 2.0.1 on 2018-03-15 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0024_auto_20180308_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='sealed_format',
        ),
        migrations.AddField(
            model_name='set',
            name='big_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='big_sets', to='card.Set'),
        ),
        migrations.AddField(
            model_name='set',
            name='small_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='small_sets', to='card.Set'),
        ),
        migrations.AddField(
            model_name='set',
            name='third_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_sets', to='card.Set'),
        ),
        migrations.AlterField(
            model_name='card',
            name='in_pack',
            field=models.BooleanField(default=True),
        ),
    ]
